package com.aris.voice.actions

import com.aris.voice.core.ArisResult
import com.aris.voice.domain.PlanStep

/**
 * Executes a full Plan after receiving an approved Decision.
 */
interface IPlanExecutor {
    suspend fun executePlan(
        decision: com.aris.voice.domain.Decision,
        onProgress: (com.aris.voice.domain.StepExecutionResult) -> Unit = {}
    ): com.aris.voice.domain.ExecutionResult

    fun cancelExecution()
}

/**
 * Executes a single discrete PlanStep generated by the Brain.
 */
interface IActionExecutor {
    suspend fun executeStep(step: PlanStep): ArisResult<String>
}

/**
 * Handles physical layout interactions such as simulated clicks, swiping, scrolling, and typing.
 */
interface IGestureExecutor {
    suspend fun performClick(x: Int, y: Int): ArisResult<Unit>
    suspend fun performSwipe(startX: Int, startY: Int, endX: Int, endY: Int, durationMs: Long): ArisResult<Unit>
    suspend fun performScroll(direction: String): ArisResult<Unit>
    suspend fun performType(text: String): ArisResult<Unit>
}

/**
 * Executes device state configurations and native platform utilities.
 */
interface ISystemActionExecutor {
    suspend fun performBack(): ArisResult<Unit>
    suspend fun performHome(): ArisResult<Unit>
    suspend fun toggleSetting(settingKey: String, enable: Boolean): ArisResult<Unit>
    suspend fun controlMedia(command: String): ArisResult<Unit>
}

/**
 * Handles package execution, launching apps directly or matching deep link targets.
 */
interface IAppLauncher {
    suspend fun launchApp(packageName: String): ArisResult<Unit>
    suspend fun launchDeepLink(uri: String): ArisResult<Unit>
}
