package com.aris.voice.data

import com.google.firebase.Timestamp
import java.util.Date

/**
 * Data model for memories fetched directly from Firestore.
 * This class serves as the network equivalent of the local `Memory` Room entity.
 */
data class UserMemory(
    val id: String = "",
    val text: String = "",
    val source: String = "User",
    val createdAt: Date = Date(),
    val memoryType: String = "GENERAL",
    val importanceScore: Int = 50
) {
    /**
     * Default constructor required for Firebase deserialization.
     */
    constructor() : this("", "", "User", Date(), "GENERAL", 50)
    
    /**
     * Converts this UserMemory from Firestore into a local Room Memory entity.
     */
    fun toLocalMemory(): Memory {
        val parsedType = MemoryType.fromString(memoryType)
        return Memory(
            originalText = text,
            embedding = "[]", // Needs to be generated by EmbeddingService later
            memoryType = parsedType.name,
            importanceScore = importanceScore.coerceIn(0, 100),
            source = source,
            timestamp = createdAt.time
        )
    }
}
